# ADW configuration file

# Root directory of the project (default: current directory)
project_root: "."

# Directory where source code lives (default: "src")
source_dir: "src"

# Directory where tests live (default: "tests")
test_dir: "tests"

# Command to run tests (default: "uv run pytest")
test_command: "uv run pytest"

# Directory for ADW logs and plans (default: "ai_docs")
docs_dir: "ai_docs"

# Language of the project (default: "python")
language: "python"

# ============================================================================
# OPENCODE HTTP API MIGRATION - FEATURE FLAGS & CONFIGURATION
# ============================================================================
# 
# This section controls the gradual migration from AWS Bedrock + Copilot CLI
# to OpenCode HTTP API with intelligent model routing.
#
# Status: In Development (Epic 1-5)
# Created: January 7, 2026
# ============================================================================

# ============================================================================
# MIGRATION FEATURE FLAGS (DEPRECATED - Not Used in Current Implementation)
# ============================================================================
# 
# NOTE: These flags are defined for documentation purposes but are NOT
# currently checked by the code. The system now uses OpenCode HTTP API
# directly for all operations without conditional logic.
#
# The code was migrated to use OpenCode directly rather than gradual
# feature-flag-based rollout. These flags are kept as reference documentation.
#
# If implementing conditional behavior in the future, these are the toggles.
#
# Status: Phase 0 - Direct OpenCode HTTP path confirmed
# Created: January 7, 2026
# Updated: January 9, 2026 (marked deprecated)
# ============================================================================

migration:
  # DEPRECATED: These flags are not used by the code
  # The system now uses OpenCode HTTP API for all operations
  use_opencode_for_lightweight: true      # Always enabled (via OpenCode HTTP)
  use_opencode_for_heavy_lifting: true    # Always enabled (via OpenCode HTTP)
  disable_opencode: false                 # Never disable (no fallback exists)

# ============================================================================
# OPENCODE HTTP API CONFIGURATION (Phase 0 - Active)
# ============================================================================
# Configure the OpenCode HTTP server endpoint, models, and behavior
# This is the PRIMARY and ONLY execution path for all LLM operations

opencode:
  # HTTP server endpoint where OpenCode is running
  # Default: localhost:4096 (assumes: opencode serve --port 4096)
  # Update if using different host/port
  server_url: "http://localhost:4096"

  # Model selection per task type
  models:
    # Heavy lifting: code implementation, test fixing, code reviews
    # Uses: Claude Sonnet 4 (most capable for code tasks via GitHub Copilot)
    # Model ID format: github-copilot/model-name
    heavy_lifting: "github-copilot/claude-sonnet-4"

    # Lightweight: planning, classification, document generation
    # Uses: Claude Haiku 4.5 (faster for lightweight tasks via GitHub Copilot)
    # Model ID format: github-copilot/model-name
    lightweight: "github-copilot/claude-haiku-4.5"

  # Timeout settings (in seconds)
  timeout: 600                 # 10 minutes for heavy code operations
  lightweight_timeout: 60      # 1 minute for planning/classification
  
  # Retry configuration
  max_retries: 3              # Number of retries on transient failures
  retry_backoff: 1.5          # Exponential backoff multiplier

  # Session management
  reuse_sessions: false       # Create new session for each operation
                              # Set to true for performance optimization (experimental)

  # Connection settings
  connection_timeout: 30      # Seconds to wait for initial connection
  read_timeout: 600           # Seconds to wait for response completion

# ============================================================================
# NOTES FOR DEVELOPMENT
# ============================================================================
#
# PHASE 0 STATUS (January 9, 2026):
# - Deluxe LLM fallback permanently removed (token expired Dec 30, 2025)
# - All operations route DIRECTLY to OpenCode HTTP API (no fallback chain)
# - GitHub Copilot models verified and accessible:
#   * Claude Sonnet 4 (heavy lifting: code implementation, test fixing, reviews)
#   * Claude Haiku 4.5 (lightweight: planning, classification, document generation)
# - No feature flags needed - OpenCode is the ONLY execution path
# - All 95 existing tests passing with new direct-path architecture
# - Configuration clean and simplified - no hybrid state, no fallback logic
#
# PREREQUISITES TO RUN ADWS:
# 1. OpenCode Server running: opencode serve --port 4096
# 2. OpenCode Authentication: opencode auth login
# 3. Copilot CLI installed: copilot --version (for implement_plan, test_fix, review)
# 4. Jira credentials in .env or environment:
#    - JIRA_SERVER
#    - JIRA_USERNAME
#    - JIRA_API_TOKEN
#
# QUICK START:
# 1. Start OpenCode: opencode serve --port 4096
# 2. Authenticate: opencode auth login
# 3. Run ADWS: uv run scripts/adw_cli.py [options]
# 4. Check logs: ai_docs/logs/[adw_id]/[agent]/
#
# EMERGENCY ROLLBACK:
# If needed, disable OpenCode and use fallback (if implemented):
#   Set disable_opencode: true (currently has no fallback - define strategy)
# ============================================================================
