# ADW configuration file

# Root directory of the project (default: current directory)
project_root: "."

# Directory where source code lives (default: "src")
source_dir: "src"

# Directory where tests live (default: "tests")
test_dir: "tests"

# Command to run tests (default: "uv run pytest")
test_command: "uv run pytest"

# Directory for ADW logs and plans (default: "ai_docs")
docs_dir: "ai_docs"

# Language of the project (default: "python")
language: "python"

# ============================================================================
# OPENCODE HTTP API MIGRATION - FEATURE FLAGS & CONFIGURATION
# ============================================================================
# 
# This section controls the gradual migration from AWS Bedrock + Copilot CLI
# to OpenCode HTTP API with intelligent model routing.
#
# Status: In Development (Epic 1-5)
# Created: January 7, 2026
# ============================================================================

# ============================================================================
# MIGRATION FEATURE FLAGS (DEPRECATED - Not Used in Current Implementation)
# ============================================================================
# 
# NOTE: These flags are defined for documentation purposes but are NOT
# currently checked by the code. The system now uses OpenCode HTTP API
# directly for all operations without conditional logic.
#
# The code was migrated to use OpenCode directly rather than gradual
# feature-flag-based rollout. These flags are kept as reference documentation.
#
# If implementing conditional behavior in the future, these are the toggles.
#
# Status: Phase 0 - Direct OpenCode HTTP path confirmed
# Created: January 7, 2026
# Updated: January 9, 2026 (marked deprecated)
# ============================================================================

migration:
  # DEPRECATED: These flags are not used by the code
  # The system now uses OpenCode HTTP API for all operations
  use_opencode_for_lightweight: true      # Always enabled (via OpenCode HTTP)
  use_opencode_for_heavy_lifting: true    # Always enabled (via OpenCode HTTP)
  disable_opencode: false                 # Never disable (no fallback exists)

# ============================================================================
# OPENCODE HTTP API CONFIGURATION (Phase 0 - Active)
# ============================================================================
# Configure the OpenCode HTTP server endpoint, models, and behavior
# This is the PRIMARY and ONLY execution path for all LLM operations

opencode:
  # HTTP server endpoint where OpenCode is running
  # Default: http://localhost:4096 (assumes you ran: opencode serve --port 4096)
  # Example for a custom host/port: "http://opencode.mycompany.internal:8080"
  # If you host OpenCode behind TLS, use https://my-opencode-host:443
  server_url: "http://localhost:4096"

  # Model selection per task type
  # Use full OpenCode model IDs. Examples below reference GitHub Copilot-hosted
  # Claude models which are recommended for this project:
  models:
    # Heavy lifting: code implementation, test fixing, code reviews
    # Example: "github-copilot/claude-sonnet-4"
    # Notes: Sonnet 4 is more capable for code generation and analysis. Use for
    # task_type values: implement, test_fix, review
    heavy_lifting: "github-copilot/claude-sonnet-4"

    # Lightweight: planning, classification, document generation
    # Example: "github-copilot/claude-haiku-4.5"
    # Notes: Haiku 4.5 is faster and cheaper; use for task_type values: classify,
    # extract_adw, plan, branch_gen, commit_msg, pr_creation
    lightweight: "github-copilot/claude-haiku-4.5"

  # Timeout settings (in seconds)
  # timeout: used for heavy / long-running operations (e.g. implement, review)
  # lightweight_timeout: used for quick operations (e.g. classify, branch_gen)
  # Example: set timeout: 900 for very large code generation jobs
  timeout: 1800                # 30 minutes for heavy code operations (default)
  lightweight_timeout: 60      # 1 minute for planning/classification (default)
  
  # Retry configuration
  # max_retries: number of retry attempts for transient failures (connect/timeouts/5xx)
  # retry_backoff: multiplier used for exponential backoff (delay = base * backoff^(attempt-1))
  # Example: max_retries: 5 and retry_backoff: 2.0 (1s, 2s, 4s, 8s, 16s delays)
  max_retries: 3
  retry_backoff: 1.5

  # Session management
  # reuse_sessions: when true, the client will attempt to reuse OpenCode sessions
  # between calls which can improve throughput. When false, a fresh session is
  # created per operation which is safer for debugging and isolation.
  # Note: set to true in CI/perf-sensitive environments only after validation.
  reuse_sessions: false

  # Connection settings
  # connection_timeout: how long (seconds) to wait for initial TCP/connect
  # read_timeout: how long (seconds) to wait for the full response body
  # Example: for very large code-review responses you may want read_timeout: 1200
  connection_timeout: 30
  read_timeout: 1800

  # OPTIONAL: Example override snippets (document-only)
  # You can override these settings per-environment. Example YAML snippets:
  #
  # production:
  #   opencode:
  #     server_url: "https://opencode.example.com"
  #     models:
  #       heavy_lifting: "github-copilot/claude-sonnet-4"
  #       lightweight: "github-copilot/claude-haiku-4.5"
  #     timeout: 900
  #     lightweight_timeout: 90
  #     max_retries: 5
  #     retry_backoff: 2.0
  #     reuse_sessions: true
  #
  # local-dev:
  #   opencode:
  #     server_url: "http://localhost:4096"
  #     models:
  #       heavy_lifting: "github-copilot/claude-sonnet-4"
  #       lightweight: "github-copilot/claude-haiku-4.5"
  #     timeout: 600
  #     lightweight_timeout: 60
  #     max_retries: 2
  #     retry_backoff: 1.5
  #     reuse_sessions: false

  # Guidance:
  # - For most users, the defaults above will work (local OpenCode on port 4096).
  # - If you see authentication or model-not-found errors, verify OpenCode auth
  #   (opencode auth login) and that you have a GitHub Copilot subscription.
  # - Increase timeout/read_timeout for very large code synthesis tasks.
  # - Use reuse_sessions=true to improve throughput in CI but validate session
  #   lifetime and cookie handling for your OpenCode deployment.

# ============================================================================
# NOTES FOR DEVELOPMENT
# ============================================================================
#
# PHASE 0 STATUS (January 9, 2026):
# - Deluxe LLM fallback permanently removed (token expired Dec 30, 2025)
# - Epic 1 (OpenCode HTTP Client): ✅ COMPLETE
# - Epic 2 (Planning/Classification): ✅ COMPLETE - Uses OpenCode HTTP API
# - Epic 3 (Code Execution): ⏳ IN PROGRESS - Still uses Copilot CLI (migration pending)
# - GitHub Copilot models verified and accessible:
#   * Claude Sonnet 4 (via github-copilot/ prefix: code, testing, reviews)
#   * Claude Haiku 4.5 (via github-copilot/ prefix: planning, classification)
# - Planning & Classification: Direct OpenCode HTTP API (no fallback chain)
# - Code Execution: Still uses Copilot CLI (requires copilot command in PATH)
# - All 95 existing tests passing with current architecture
#
# PREREQUISITES TO RUN ADWS:
# 1. OpenCode Server running: opencode serve --port 4096
# 2. OpenCode Authentication: opencode auth login
# 3. Copilot CLI installed: copilot --version (required until Epic 3 migration complete)
# 4. Jira credentials in .env or environment:
#    - JIRA_SERVER
#    - JIRA_USERNAME
#    - JIRA_API_TOKEN
#
# QUICK START:
# 1. Start OpenCode: opencode serve --port 4096
# 2. Authenticate: opencode auth login
# 3. Install Copilot CLI: brew install copilot OR npm install -g @github/copilot-cli
# 4. Run ADWS: uv run scripts/adw_cli.py [options]
# 5. Check logs: ai_docs/logs/[adw_id]/[agent]/
#
# EPIC 3 MIGRATION STATUS:
# When Epic 3 (Code Execution Operations Migration) is complete, these operations
# will migrate from Copilot CLI to OpenCode HTTP API:
#   - implement_plan() → will use OpenCode HTTP API with Claude Sonnet 4
#   - resolve_failed_tests() → will use OpenCode HTTP API with Claude Sonnet 4
#   - run_review() → will use OpenCode HTTP API with Claude Sonnet 4
# After Epic 3, Copilot CLI will no longer be required.
# ============================================================================
